### ISSUE TITLE
Could you also demonstrate an example for signing up

### ISSUE THREAD

**Issue by jasjuang** [sibtc/simple-django-login#1]
This is by far the most beginner friendly tutorial for user login I've came across. Thanks a lot for putting this up.

Could you also demonstrate an example for allowing the user to sign up?

**Comment by vitorfs** [comment]
Hey there :-)
Thanks for the comment! And also thanks for the suggestion! I will address it in a future post 👍

**Comment by vitorfs** [comment]
The link is here btw:

https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
